<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
->appendFile($this->basePath('assets/global/plugins/jquery-validation/js/jquery.validate.min.js'))
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));
$this->headScript()->appendFile($this->basePath('js/setup/travel-exp-class/edit.js'));

?>
<script>
    document.addTravelClassLink = '<?= $this->url("travelExpenseClass", ["action" => "add"]) ?>';
    document.editTravelCategoryLink = '<?= $this->url("travelExpenseClass", ["action" => "edit",'id' => $id]) ?>';

</script>
<style>
    .error{
        color: red;
    }
</style>

<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\travelExpenseClass')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>Update
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">
                <form action="" id="travelClassForm" method="POST">
                <div class=" row">      
                <div class="col-sm-4">
                     <div class="form-group">
                        <label for="associateName">Category Name</label>
                        <span class="required" aria-required="true">*</span>
                        <input type="text" id="categoryName"  name="categoryName" class="form-control" value="<?php echo $detail['CATEGORY_NAME'];?>" autocomplete="off" required>                                
                    </div>
                </div>

                <div class="col-sm-4">
                    <div class="form-group">
                        <label for="associateName">Allowance % </label>
                        <span class="required" aria-required="true">*</span>
                        <input type="number" id="allowancePercentage" name="allowancePercentage" value="<?php echo $detail['ALLOWANCE_PERCENTAGE'];?>" class="form-control" autocomplete="off" required>
                    </div>              
                    </div>
                <input type="submit" name="submit" id="submit" class="btn btn-success" value="Submit" autocomplete="off" style="margin-top:2.5rem ; margin-left:4rem;">                
            </div>
          </form> 
        </div>
    </div>
</div>
