<?php
$this->headScript()->appendFile($this->basePath('js/Payroll/salary-sheet/payslip.js?1'));
?>
<script>
    document.getFiscalYearMonthLink = '<?php echo $this->url('salarySheet', ['action' => 'getFiscalYearMonth']); ?>';
    document.getSearchDataLink = '<?php echo $this->url('salarySheet', ['action' => 'getSearchData']); ?>';
    document.salaryType = <?php echo $salaryType; ?>;
    document.sendPayslipEmailLink = '<?php echo $this->url('salarySheet', ['action' => 'sendPayslipEmail']); ?>';
    document.wsExchangeRate = '<?php echo $this->url('salarySheet', ['action' => 'getExchangeRate']); ?>';
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\salarySheet')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<div class="portlet box yellow">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-money"></i>Payslip
        </div>
        <div class="actions">
            <div class="btn-group">
                <a class="btn btn-sm blue-soft" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                    <i class="fa fa-copy"></i> Tools
                    <i class="fa fa-angle-down "></i>
                </a>
                <ul class="dropdown-menu pull-right">
                    <li>
                        <a href="javascript:;" id="excelExport">
                            <i class="fa fa-file-excel-o"></i>
                            Export to Excel
                        </a>
                    </li>
                    <li>
                        <a href="javascript:;" id="pdfExport">
                            <i class="fa fa-file-pdf-o"></i>
                            Export to PDF
                        </a>
                    </li>
                </ul>
            </div>
        </div>

    </div>
    <div class="portlet-body">
        <div class="row">
            <div class="col-sm-2">
                <select id="fiscalYearId">
                </select>
            </div>
            <div class="col-sm-2">
                <select id="monthId">
                </select>
            </div>
            <div class="col-sm-2">
                <select id="employeeId">
                </select>
            </div>
            <div class="col-sm-2">
                <!--<label>Salary Type</label>-->
                <select class="form-control" name="salaryType" id="salaryTypeId">
                </select>
            </div>
            <?php if ($allowExchangeRate == 'Y') { ?>
                <div style="padding-right: 6px;font-weight: 500;" class="col-sm-2">
                    <label for="" class="radio-inline">
                        <input type="radio" name="exchangeRate" value="1" checked>Dollar
                    </label>
                    <label for="" class="radio-inline">
                        <input type="radio" name="exchangeRate" value="0">Nepali
                    </label>
                </div>
                <div class="col-sm-2">
                    <input type="text" id="exchangeRateVal" disabled="disabled" class="form-control" placeholder="Exchange Rate" />
                </div>
            <?php } ?>
            <div class="col-sm-2">
                <button id="viewBtn" class="btn btn-info pull-right" style="cursor: pointer;">View</button>
            </div>
            <?php if ($sendPayslipEmail == 'Y') { ?>

                <div class="col-sm-2" style="margin-left: -5rem;">
                    <button id="mailBtn" class="btn btn-warning pull-right">Send mail</button>
                </div>
            <?php } ?>
        </div>


        <div id="paySlipView" class="margin-top-10">
            <table class="table table-bordered" id="employee-detail">
                <tr>
                    <td colspan="4">
                        <h3><b><span id="yearMonthDetails"></span></b></h3>
                    </td>
                </tr>
                <tr>
                    <td>Employee Name</td>
                    <td key="FULL_NAME"></td>
                    <td>Date of Join</td>
                    <td key="JOIN_DATE"></td>
                </tr>
                <tr>
                    <td>Marital Status</td>
                    <td key="MARITAL_STATUS_DESC"></td>
                    <td>Department</td>
                    <td key="DEPARTMENT_NAME"></td>
                </tr>

                <tr>
                    <td>CIT No</td>
                    <td key="ID_RETIREMENT_NO"></td>
                    <td>A/c No</td>
                    <td key="ACCOUNT_NO"></td>
                </tr>


                <tr>
                    <td>PF No</td>
                    <td key="ID_PROVIDENT_FUND_NO"></td>
                    <td>PAN No</td>
                    <td key="ID_PAN_NO"></td>

                </tr>

                <tr>
                    <td>Position Name</td>
                    <td key="POSITION_NAME"></td>
                    <?php if ($allowExchangeRate == 'Y') { ?>
                        <td>Exchange Rate</td>
                        <td key="EXCHANGE_RATE"></td>
                    <?php } ?>
                </tr>
            </table>
            <table class="table table-bordered">
                <thead>
                    <th colspan="2" style="font-size: 14px"><b>Addition</b></th>
                    <th colspan="2" style="font-size: 14px"><b>Deduction</b></th>
                </thead>
                <tbody id="paySlipBody">
                </tbody>
            </table>
        </div>
    </div>
</div>