<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));

$this->headScript()->appendFile($this->basePath('js/angular.min.js'));
$this->headScript()->appendFile($this->basePath('js/SelfService/new-travel-request/add.js'));
$this->headScript()->appendFile($this->basePath('js/SelfService/travel-request/add.js?1'));

$form->setAttribute('role', 'form');
$form->setAttribute('id', 'travelRequest-form');

$fromDate = $form->get('fromDate');
$toDate = $form->get('toDate');
$destination = $form->get('destination');
$departure = $form->get('departure');
$requestedAmount = $form->get('requestedAmount');
$requestedType = $form->get('requestedType');
$requestedType->setValueOptions($requestTypes);
$transportType = $form->get('transportType');
$transportType->setValueOptions($transportTypes);
$purpose = $form->get('purpose');
$remarks = $form->get('remarks');
$noOfDays = $form->get('noOfDays');

$submit = $form->get('submit');
$submit->setAttribute('value', 'SUBMIT');

$form->setAttribute('action', $this->url('newtravelrequest', ['action' => 'add']));
$form->setAttribute('enctype', 'multipart/form-data');

$form->prepare();
?>
 <?php  $all_data = json_encode(file_get_contents("https://gist.githubusercontent.com/aaronhayes/5fef481815ac75f771d37b16d16d35c9/raw/edbec8eea5cc9ace57a79409cc390b7b9bcf24f6/currencies.json")); ?>
<script>
    document.url = '<?= $this->url("restful", ["action" => "index"]) ?>';
    document.currencyList = <?php echo json_decode($all_data) ?>;
</script>
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\travelRequest')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>

<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>
        
    </script>
<?php } ?>
<div class="col-sm-12">
    <div class="portlet box custom-box">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-user"></i>New Entry
            </div>
            <div class="actions">
                <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
            </div>
        </div>
        <div class="portlet-body">
            <div class="form-group">
                <input type="hidden" id="employeeId" value="<?php echo $employeeId; ?>"/>
            </div>
            <?php
            print $this->form()->openTag($form);
            ?>
            <div class="row">
                <div class="col-sm-4">
                    <div class="form-group">
                        <label for="associateName">Associate Name</label>
                        <input type="text" class="form-control" value="<?php echo $employeeDetails['FULL_NAME'] ?>" disabled>
                    </div>               
                </div>
                <div class="col-sm-4">
                    <div class="form-group">
                        <label for="associateName">Associate HRIS ID</label>
                        <input type="text" class="form-control" value="<?php echo $employeeDetails['USER_NAME'] ?>" disabled>
                    </div>               
                </div>
                <div class="col-sm-4">
                    <div class="form-group">
                        <label for="associateName">Function</label>
                        <input type="text" class="form-control" value="<?php echo $employeeDetails['DEPARTMENT_NAME'] ?>" disabled>
                    </div>               
                </div>
            </div>  
            <div class="row">
               
                <div class="col-sm-4">
                    <div class="form-group">
                        <label for="associateName">Designations</label>
                        <input type="text" class="form-control" value="<?php echo $employeeDetails['DESIGNATION_TITLE'] ?>" disabled>
                    </div>               
                </div>
               
                <div class="col-sm-4">
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <?php print $this->formLabel($fromDate); ?>
                                <span class="required" aria-required="true">*</span>
                                <?php print $this->formElement($fromDate); ?>
                                <?php print $this->formElementErrors()->render($fromDate, ['class' => 'help-block']); ?>
                            </div>
                        </div>     
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="nepaliStartDate">&nbsp;</label>
                                <div class="input-group">
                                    <input type="text" name="nepaliStartDate" id="nepaliStartDate1"
                                        class="form-control" value="">
                                </div>
                            </div>
                        </div>     
                    </div> 
                </div>
                <div class="col-sm-4">
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <?php print $this->formLabel($toDate); ?>
                                <span class="required" aria-required="true">*</span>
                                <?php print $this->formElement($toDate); ?>
                                <?php print $this->formElementErrors()->render($toDate, ['class' => 'help-block']); ?>
                            </div>
                        </div>     
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="nepaliEndDate">&nbsp;</label>
                                <div class="input-group">
                                    <input type="text" name="nepaliEndDate" id="nepaliEndDate1"
                                        class="form-control" value="">
                                </div>
                            </div>
                        </div>     
                    </div>  
                </div>
            </div>  
            <div class=" row">
                <div class="col-sm-4">
                    <div class="form-group">
                            <label for="approver">Approver</label>
                            <input type="text"  class="form-control" value="<?php echo $employeeDetails['APPROVER_NAME'] ?>" disabled>
                    </div>               
                </div>
                <div class="col-sm-4">
                    <div class="form-group">
                        <label for="associateName">Travel Type </label>
                        <select name="travelType" class="form-control" onchange="travelTypeForAdvance()" id="travelType" required>
                            <option value=""  selected disabled>Select the travel type</option>
                            <option value="LTR">Domestic</option>
                            <option value="ITR">International</option>
                        </select>
                    </div>               
                </div>
                <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($departure); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($departure); ?>
                            <?php print $this->formElementErrors()->render($departure, ['class' => 'help-block']); ?>
                        </div>               
                    </div>
            </div>
                <div class=" row">
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($destination); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($destination); ?>
                            <?php print $this->formElementErrors()->render($destination, ['class' => 'help-block']); ?>
                        </div>               
                    </div>


                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($purpose); ?>
                            <?php print $this->formElement($purpose); ?>
                            <?php print $this->formElementErrors()->render($purpose, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div
                            class="form-group required <?= empty($noOfDays->getMessages()) ? "" : "error" ?>">
                                <?php print $this->formLabel($noOfDays); ?>
                            <span class="required" aria-required="true">*</span>
                            <?php print $this->formElement($noOfDays); ?>
                            <span id="errorMsg" style="font-size:11px; color:red;"></span>
                        </div>
                        <?php print $this->formElementErrors()->render($noOfDays, ['class' => 'help-block error']); ?>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($remarks); ?>
                            <?php print $this->formElement($remarks); ?>
                            <?php print $this->formElementErrors()->render($remarks, ['class' => 'help-block']); ?>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <?php print $this->formLabel($transportType); ?>
                            <?php print $this->formElement($transportType); ?>
                            <?php print $this->formElementErrors()->render($transportType, ['class' => 'help-block']); ?>
                        </div> 
                    </div>
                </div>

                <div class=" row">
                    
                    
                    <div class="domestic"> 
                       
                    </div>
                    <div class="international"> 
                       
                    </div>
                </div>

                <?php
                print $this->formSubmit($submit);
                ?>
           
                <button id="reset" type="reset" class="btn default btn-sm hris-reset-btn">Reset<i class="fa fa-refresh"></i></button>
           
                <?php
                print $this->form()->closeTag();
                ?>
        </div>

    </div>
</div>
