<?php
$this->headLink()
        ->appendStylesheet($this->basePath('assets/global/plugins/ladda/ladda-themeless.min.css'))
        ->appendStylesheet($this->basePath('dropzone/dropzone.min.css'))
        ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
        ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
        ->appendFile($this->basePath('dropzone/dropzone.min.js'))
        ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));
$this->headScript()->appendFile($this->basePath('assets/global/plugins/combodate/js/moment.min.js'));
$this->headScript()->appendFile($this->basePath('assets/global/plugins/combodate/js/combodate.js'));
$this->headScript()->appendFile($this->basePath('assets/global/plugins/ladda/spin.min.js'));
$this->headScript()->appendFile($this->basePath('assets/global/plugins/ladda/ladda.min.js'));
$this->headScript()
        ->appendFile($this->basePath('js/SelfService/travel-request/expense-add.js'));
        // ->appendFile($this->basePath('js/angular.min.js'));
        // ->appendFile($this->basePath('js/SelfService/travel-request/expenseDtlController.js'));
?>
 <?php  $all_data = json_encode(file_get_contents("https://gist.githubusercontent.com/aaronhayes/5fef481815ac75f771d37b16d16d35c9/raw/edbec8eea5cc9ace57a79409cc390b7b9bcf24f6/currencies.json")); ?>
<script>
    document.transportTypes = '<?php json_encode($transportTypes)  ?>';
    document.urlExpenseAdd = '<?= $this->url("travelRequest", ["action" => "expenseAdd"]) ?>';
    document.urlExpense = '<?= $this->url("travelRequest", ["action" => "expense"]) ?>';
    document.urlExpenseDetailList = '<?= $this->url("travelRequest", ["action" => "expenseDetailList"]) ?>';
    document.currencyList = <?php echo json_decode($all_data) ?>;
    document.urlDeleteExpenseDetail = '<?= $this->url("travelRequest", ["action" => "deleteExpenseDetail"]) ?>';
    document.uploadUrl = '<?= $this->url("travelRequest", ["action" => "fileUpload"]); ?>';
    document.pushDCFileLink = '<?php echo $this->url('travelRequest', ['action' => 'pushDCFileLink']); ?>';
    document.getLineTotal = '<?php echo $this->url('travelRequest', ['action' => 'getLineTotal']); ?>';
    document.expenseItrHeads =<?=json_encode($expenseItrHeads);?>;
        document.expenseLtrHeads =<?=json_encode($expenseLtrHeads);?>;
</script>;
<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\travelRequest')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>
<?php
if ($this->messages && (sizeof($this->messages) > 1)) {
    print '<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>Warning!</strong> ';
    print $this->messages[1];
    print '</div>';
}
?>
<?php if ($this->messages) { ?>
    <script>
        document.messages =<?php echo json_encode($this->messages); ?>;
      
    </script>
<?php } ?>
<div class="row margin-top-20" ng-app="hris" ng-controller="expenseDtlController">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-user"></i>Expenses Reimbursement (ER)
                </div>
            </div>
            <div class="portlet-body div-font-11">
                <form name="travelExpenseForm" id="travelRequest-form"  method="post">
                    <input type="hidden" id="travelId" value="<?php echo $id; ?>" />
                    <div class="row">
                        <div class="col-xs-12 col-sm-4 col-md-4 col-box bottomgap">
                            <table>
                                <tr>
                                    <td width="40%">
                                        <label for="purpose">Purpose :</label> 
                                    </td>
                                    <td>
                                        <input type="text" disabled="disabled" value="<?php echo $detail['PURPOSE']; ?>" name="purpose" required="required" id="purpose" class="form-control">
                                    </td>
                                </tr>
                            </table>
                        </div>

                        <div class="col-xs-12 col-sm-4 col-md-4 col-box bottomgap">
                            <table>
                                <tr>
                                    <td width="40%">
                                        <label for="advanceAmount">Advance Amount :</label> 
                                    </td>
                                    <td>
                                        <input type="text" disabled="disabled" value="<?php echo $detail['REQUESTED_AMOUNT']; ?>" name="advanceAmount" required="required" id="advanceAmount" class="form-control">
                                    </td>
                                </tr>
                            </table>
                        </div>
                        <div class="col-xs-12 col-sm-4 col-md-4 col-box bottomgap">
                            <table>
                                <tr>
                                    <td width="40%">
                                        <label for="departure">Departure :</label> 
                                    </td>
                                    <td>
                                        <input type="text" disabled="disabled" value="<?php echo $detail['DEPARTURE'] ?>" name="departure" required="required" id="departure" class="form-control">
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                    <div class="row">
                           <div class="col-xs-12 col-sm-4 col-md-4 col-box bottomgap">
                            <table>
                                <tr>
                                    <td width="40%">     
                                        <label for="destination">Destination :</label> 
                                    </td>
                                    <td>
                                        <input type="text" disabled="disabled" value="<?php echo $detail['DESTINATION'] ?>" name="destination" required="required" id="destination" class="form-control">
                                    </td>
                                </tr>
                            </table>
                        </div>
                        <div class="col-xs-12 col-sm-4 col-md-4 col-box bottomgap">
                            <table>
                                <tr>
                                    <td width="40%">
                                        <label for="departureDate">Departure Date :</label>
                                    </td>
                                    <td>
                                        <input type="text" disabled="disabled" value="<?php echo $detail['FROM_DATE'] ?>" required="required" name="departureDate" id="departureDate" class="departureDate form-control">
                                    </td>
                                </tr>
                            </table>
                        </div>

                        <div class="col-xs-12 col-sm-4 col-md-4 col-box bottomgap">
                            <table>
                                <tr>
                                    <td width="40%">
                                        <label for="employeeCode">Returned Date :</label> 
                                    </td>
                                    <td>
                                        <input type="text" disabled="disabled" value="<?php echo $detail['TO_DATE'] ?>" required="required" name="returnedDate" id="returnedDate" class="returnedDate form-control"> 
                                    </td>
                                </tr>
                            </table>
                        </div>

                        <div class="col-xs-12 col-sm-4 col-md-4 col-box bottomgap">
                        </div>

                    </div>
                   
                    <?php 
                        if (trim($detail['TRAVEL_TYPE']) == "LTR") { ?>
                            <div class="margin-top-10 scrollbar-horizantal" id="domesticConfigTable">
                                <div class="row" >
                                    <div style="margin-left: 20px" >
                                        <table id="domesticConfigTable" class="table table-bordered tableForAll">
                                            <thead>
                                                <tr>
                                                    <th colspan="12" style="text-align:center; font-weight:bold; font-size:15px;">Domestic Travel</th>
                                                </tr>
                                                <tr>
                                                <th>Action</th> 
                                                <th>ER Type</th>       
                                                <th>Location</th>       
                                                <th>Date</th>       
                                                <th>Ticket/Bill No</th>
                                                <th>Expense Head</th>
                                                <th>Amount</th>
                                                <th>Exchange Rate</th>
                                                <th>Currency</th>     
                                                <th>Remarks</th>  
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td></td>
                                                    <td>
                                                        <select name="erTypeL[]" id="" class="erTypeL form-control" style="width:13rem ;" required>
                                                            <option value="">Select ER Type</option>
                                                            <option value="EP">Employeee Paid</option>
                                                            <option value="CP">Company Paid</option>
                                                        </select>
                                                    </td>
                                                    <td>
                                                        <input type="text" name="locFrom[]"   class="locFrom form-control" style="width:12rem ;"> 
                                                    </td>
                                                
                                                    <td>
                                                        <input type="text" name="arrDate[]"   class="arrDate form-control" style="width:12rem ;"> 
                                                    </td>
                                                    
                                                    <td>
                                                        <input type="text" name="ticketNo[]"  class="ticketNo form-control"> 
                                                    </td> 
                                                
                                                    <td>
                                                        <!-- <input type="text" name=""  class="ticketNo form-control">  -->
                                                        <select name="expenseHead[]" id="expensehead">
                                                            <?php  foreach($expenseHeads as $expenseLtrHead) { ?>
                                                                <option value="<?php echo $expenseLtrHead['gl'] ?>"><?php echo $expenseLtrHead['name'] ?></option>
                                                            <?php } ?>
                                                        </select>
                                                    </td>
                                                    <td>
                                                        <input type="number" name="amountExp[]" step="0.001"  class="addTotalExp">
                                                    </td>
                                                    <td>
                                                        <input type="number" name="conversionRate[]" class="exchangeRate" value="1" step="0.001" readonly>
                                                    </td>
                                                    <td>
                                                        <input type="text" name="currency[]" value="NPR" readonly>
                                                    </td>
                                                    <td>
                                                        <div>
                                                            <textarea name="detRemarks[]"  class="detRemarks"></textarea>
                                                        </div>
                                                    </td>

                                                </tr>
                                                
                                            </tbody>
                                        </table>

                                    </div>
                                    <div class="col-md-12" style="text-align: right;"><strong>Total Amount: <input type="number" id="totalAmountExp" value="0"></strong></div>
                                    <div class="col-md-1">
                                        <input class="deatilAddBtn btn btn-default" type="button" value="Add +" style="margin-bottom:20px;">
                                    </div>

                                </div>
                            </div>
                      <?php  } else { ?>
                        <div class="margin-top-10 scrollbar-horizantal" id="internationalConfigTable">
                        <div class="row" >
                            <div style="margin-left: 20px;" >
                                <table id="internationalConfigTable" class="table table-bordered tableForAll">
                                    <thead>
                                        <tr>
                                            <th colspan="12" style="text-align:center; font-weight:bold; font-size:15px;">International Travel</th>
                                        </tr>
                                        <tr>
                                        <th>Action</th> 
                                        <th>ER Type</th>       
                                        <th>Location</th>       
                                        <th>Date</th>       
                                        <th>Ticket/Bill No</th>
                                        <th>Expense Head</th>
                                        <th>Amount</th>
                                        <th>Exchange Rate</th>
                                        <th>Currency</th>     
                                        <th>Remarks</th>       
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td></td>
                                            <td>
                                                <select name="erTypeI[]" id="" class="erTypeL form-control" required>
                                                    <option value="">Select ER Type</option>
                                                    <option value="EP">Employeee Paid</option>
                                                    <option value="CP">Company Paid</option>
                                                </select>
                                            </td>
                                            
                                            <td>
                                                <input type="text" name="locFrom[]"   class="locFrom form-control" width="10rem"> 
                                            </td>
                                            <td>
                                                <input type="text" name="arrDate[]"   class="arrDate form-control" width="10rem"> 
                                            </td>
                                            <td>
                                                <input type="text" name="ticketNo[]"  class="ticketNo form-control" width="10rem"> 
                                            </td>   
                                            <td>
                                            <!-- <input type="text" name="expenseHead[]"  class="ticketNo form-control">  -->
                                                <select name="expenseHead[]" id="expensehead">
                                                    <?php  foreach($expenseHeads as $expenseItrHead) { ?>
                                                        <option value="<?php echo $expenseItrHead['gl'] ?>"><?php echo $expenseItrHead['name'] ?></option>
                                                    <?php } ?>
                                                </select>
                                            </td>
                                            <td>
                                                <input type="number" name="amountExp[]" step="0.001"  class="addTotalExp">
                                            </td>
                                            <td>
                                                <input type="number" name="exchangeRateInternational[]"  class="exchangeRate">       
                                            </td>
                                            <td>
                                                    <select class='currency form-control' name='currency[]' >
                                                    </select>
                                            </td>   
                                            <td>
                                                <textarea name="detRemarks[]"  class="detRemarks form-control"></textarea>
                                            </td> 
                                        </tr>
                                    </tbody>
                                </table>

                            </div>
                            <div class="col-md-12" style="text-align: right;"><strong>Total Amount: <input type="number" id="totalAmountExp" value="0"></strong></div>

                            <div class="col-md-1">
                                <input class="deatilAddBtnInternational btn btn-default" type="button" value="Add +" style="margin-bottom:20px;">
                            </div>

                        </div>
                    </div>
                     <?php   }
                        ?>
                   
                    <br><br>
                    
                    <!-- <div class= "row" style="margin-top:30px;">
                        <div class=" col-md-6 form-group">
                            <table id="fileDetailsTbl" class="table">
                                <tr>
                                    <th>Document</th>
                                    <th>&nbsp;</th>
                                    <th>Action</th>
                                </tr>
                            </table>
                        </div>
                        <div class="col-md-3">
                            <button id="addDocument" type="button" class="btn btn-primary">
                                Add
                            </button>
                        </div>
                    </div> -->
                    <div class="submit_button" style="margin-top:2%;">
                        <button class="btn btn-sm green mt-ladda-btn ladda-button mt-progress-demo" id="submitBtn" name="submit" type="submit">
                            SUBMIT
                            <i class="fa fa-edit"></i>
                        </button>    
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<!--bootstrap modal-->
<!-- <div id="documentUploadModel" class="modal fade" role="dialog">
    <div class="modal-dialog"> -->

        <!-- Modal content-->
        <!-- <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Document Upload</h4>
            </div>
            <div class="modal-body">
                <div class="modal-body" id="modal-body">
                    <div class="row">
                        <div class="col-sm-12"> -->
                            <!--<div id="dropZoneContainer" >-->
                            <!-- <div id="dropZoneContainer"  class="dropzone">
                            </div>
                            <div id="uploadErr">Please upload .pdf or .txt or .jpg or .png files only.</div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="modal-footer">
            <button id='uploadSubmitBtn' class="btn btn-primary" type="button" >OK</button>
            <button id='uploadCancelBtn' class="btn btn-warning" type="button" >Cancel</button> -->
            <!--<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>-->
        <!-- </div>
    </div>
</div> -->

