<?php
//Load JS files here
$this->headScript()->appendFile($this->basePath('js/Payroll/new-employee-map/index.js'));
$this->headLink()
    ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.common.min.css'))
    ->appendStylesheet($this->basePath('telerik_kendoui/styles/kendo.default.min.css'));

$this->headScript()
    ->appendFile($this->basePath('jszip/dist/jszip.min.js'))
    ->appendFile($this->basePath('telerik_kendoui/js/kendo.all.min.js'))
    ->appendFile($this->basePath('js/angular.min.js'))
    ->appendFile($this->basePath('js/search.js'));
?>

<script>
    document.getAccountHeadByCompany = <?php echo json_encode($accountListCompanyWise) ?>;
    document.getBranchNameByCompany = <?php echo json_encode($branchListCompanyWise) ?>;
    document.employeeListOfCompany = '<?php echo $this->url('newEmployeeMap', ['action' => 'employeeListOfCompany']); ?>';
    document.insertIntoAccCodeMap = '<?php echo $this->url('newEmployeeMap', ['action' => 'insertIntoAccCodeMap']); ?>';
    document.getMappedAccCode = '<?php echo $this->url('newEmployeeMap', ['action' => 'getMappedAccCode']); ?>';
    document.deleteLink = '<?php echo $this->url('newEmployeeMap', ['action' => 'delete']); ?>';
</script>


<div class="row margin-top-20">
    <div class="col-sm-12">

        <div class="row">
            <div class="col-sm-3">
                <label>Company</label>
                <select required class="form-control" name="company" id="company">
                    <option value='---'>---</option>
                    <?php foreach ($companyList as $key => $value) {  ?>
                        <option value='<?= $key ?>'><?= $value ?></option>
                    <?php } ?>
                </select>
            </div>
            <?php /* <div class="col-sm-3">
                                <label>Branch</label>
                                <?php print $this->formElement($branchs); ?>
                        </div> */ ?>
            <div class="col-sm-3">
                <label>Functional Type</label>
                <select class="form-control" name="functionalType" id="functionalType">
                    <option value='0'>N/A</option>
                    <?php foreach ($functionalType as $key => $value) {  ?>
                        <option value='<?= $key ?>'><?= $value ?></option>
                    <?php } ?>
                </select>
            </div>
            <div class="col-sm-3">
                <label>Pay Head</label>
                <select class="form-control" name="payHead" id="payHead">
                    <option value='---'>---</option>
                    <?php foreach ($payHeadList as $key => $value) {  ?>
                        <option value='<?= $key ?>'><?= $value ?></option>
                    <?php } ?>
                </select>
            </div>

            <div class="col-sm-3">
                <label>Account Head</label>
                <?php print $this->formElement($accounts); ?>
            </div>
            <div class="col-sm-3">
                <label>Show Sub-details</label>
                <select class="form-control" name="showSubDetail" id="showSubDetail">
                    <option value='N'>N</option>
                    <option value='Y'>Y</option>
                </select>
            </div>
        </div>

        <div class="row">
            <br>

            <div class="col-sm-2 " id="mapPayIdAndAccCode">
                <button class="btn btn-primary">Map Pay Head and Account Head</button>
            </div>
            <br>
        </div>

    </div>
</div>
<div class="row margin-top-20">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div id="employeeTableDiv">
                <div id="employeeTable">
                </div>

            </div>
        </div>
    </div>
</div>