<?php
$this->headLink()
    ->appendStylesheet($this->basePath('assets/global/plugins/ladda/ladda-themeless.min.css'));

$this->headLink()
    ->appendStylesheet($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.css'));

$this->headScript()
    ->appendFile($this->basePath('assets/global/plugins/nepalidate/nepali.datepicker.v2.1.min.js'))
    ->appendFile($this->basePath('js/nepali-datepicker-ext.js'));

$this->headScript()->appendFile($this->basePath('js/system/system-utility/re-calculateLeave.js'));

?>

<?php if($this->messages):?>
    <script>
        document.messages=<?php echo json_encode($this->messages);?>
    </script>
<?php endif;?>

<?php 
if ($this->messages){
    print '<ul class="help-block bg-danger" style="background:#f3e250;">';
    foreach ($this->messages as $message){
        print '<li>' . $message .'</li>';
    }
    print'</ul>';
}
?>

<script>
    document.employeeList=<?=json_encode($employeeList);?>;
    document.leaveList=<?=json_encode($leaveList);?>;
    document.recalLeaveLink='<?php echo $this->url('system-utility',['action' => 'reCalculateLeave']) ?>';
</script>

<div class="page-bar">
    <?= $this->navigation('Zend\Navigation\system-utility')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb') ?>
</div>



<div class="row margin-top-30">
    <div class="col-sm-12">
        <div class="portlet box custom-box">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-edit"></i>
                    Re-Calculate Leave
                </div>
                <div class="actions">
                    <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""></a>
                </div>
            </div>

            <div class="portlet-body">
                <div class="row">
                    <div class="col-sm-4">
                        <div class="row">
                            <div class="col-sm-10">
                                <div class="form-group">
                                    <label for="employeeId">Employees</label>
                                    <select  multiple  name="employeeId" id="employeeId" class="form-control">
                                    </select>
                                </div>
                            </div>  
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="row">
                            <div class="col-sm-10">
                                <div class="form-group">
                                    <label for="leaveId">Leave</label>
                                    <select name="leaveId" id="leaveId" style="width : 25rem; height: 0px" class="form-control">
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="col-sm-6">
                            <input type="button" name="submit" class="btn btn-success pull-right" style="margin-top: 23px;  height:28px !important" id="btn-recalLeave" value="Submit">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>













